//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IKanjiService
{
    
    bool ReceivePoints(int[] xcoords, int[] ycoords, System.DateTime[] times);
    
    bool MessageForDesktop(int messages);
    
    bool MessageForInputArea(int messages);
    
    int GetNewMessagesForMobile();
    
    int GetNewMessagesForDesktop();
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ReceivePoints", Namespace="http://www.japanese-coach.com")]
public partial class ReceivePointsRequest
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://www.japanese-coach.com", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
    public int[] xcoords;
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://www.japanese-coach.com", Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
    public int[] ycoords;
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://www.japanese-coach.com", Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
    public System.DateTime[] times;
    
    public ReceivePointsRequest()
    {
    }
    
    public ReceivePointsRequest(int[] xcoords, int[] ycoords, System.DateTime[] times)
    {
        this.xcoords = xcoords;
        this.ycoords = ycoords;
        this.times = times;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ReceivePointsResponse", Namespace="http://www.japanese-coach.com")]
public partial class ReceivePointsResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.japanese-coach.com", Order=0)]
    public bool ReceivePointsResult;
    
    public ReceivePointsResponse()
    {
    }
    
    public ReceivePointsResponse(bool ReceivePointsResult)
    {
        this.ReceivePointsResult = ReceivePointsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="MessageForDesktop", Namespace="http://www.japanese-coach.com")]
public partial class MessageForDesktopRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.japanese-coach.com", Order=0)]
    public int messages;
    
    public MessageForDesktopRequest()
    {
    }
    
    public MessageForDesktopRequest(int messages)
    {
        this.messages = messages;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="MessageForDesktopResponse", Namespace="http://www.japanese-coach.com")]
public partial class MessageForDesktopResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.japanese-coach.com", Order=0)]
    public bool MessageForDesktopResult;
    
    public MessageForDesktopResponse()
    {
    }
    
    public MessageForDesktopResponse(bool MessageForDesktopResult)
    {
        this.MessageForDesktopResult = MessageForDesktopResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="MessageForInputArea", Namespace="http://www.japanese-coach.com")]
public partial class MessageForInputAreaRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.japanese-coach.com", Order=0)]
    public int messages;
    
    public MessageForInputAreaRequest()
    {
    }
    
    public MessageForInputAreaRequest(int messages)
    {
        this.messages = messages;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="MessageForInputAreaResponse", Namespace="http://www.japanese-coach.com")]
public partial class MessageForInputAreaResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.japanese-coach.com", Order=0)]
    public bool MessageForInputAreaResult;
    
    public MessageForInputAreaResponse()
    {
    }
    
    public MessageForInputAreaResponse(bool MessageForInputAreaResult)
    {
        this.MessageForInputAreaResult = MessageForInputAreaResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetNewMessagesForMobile", Namespace="http://www.japanese-coach.com")]
public partial class GetNewMessagesForMobileRequest
{
    
    public GetNewMessagesForMobileRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetNewMessagesForMobileResponse", Namespace="http://www.japanese-coach.com")]
public partial class GetNewMessagesForMobileResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.japanese-coach.com", Order=0)]
    public int GetNewMessagesForMobileResult;
    
    public GetNewMessagesForMobileResponse()
    {
    }
    
    public GetNewMessagesForMobileResponse(int GetNewMessagesForMobileResult)
    {
        this.GetNewMessagesForMobileResult = GetNewMessagesForMobileResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetNewMessagesForDesktop", Namespace="http://www.japanese-coach.com")]
public partial class GetNewMessagesForDesktopRequest
{
    
    public GetNewMessagesForDesktopRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetNewMessagesForDesktopResponse", Namespace="http://www.japanese-coach.com")]
public partial class GetNewMessagesForDesktopResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.japanese-coach.com", Order=0)]
    public int GetNewMessagesForDesktopResult;
    
    public GetNewMessagesForDesktopResponse()
    {
    }
    
    public GetNewMessagesForDesktopResponse(int GetNewMessagesForDesktopResult)
    {
        this.GetNewMessagesForDesktopResult = GetNewMessagesForDesktopResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class KanjiServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<IKanjiService>, IKanjiService
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://localhost:8000/kanji/KanjiService");
    
    public KanjiServiceClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public KanjiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private ReceivePointsResponse ReceivePoints(ReceivePointsRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://www.japanese-coach.com/IKanjiService/ReceivePoints";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://www.japanese-coach.com/IKanjiService/ReceivePointsResponse";
        info.ResponseIsWrapped = true;
        ReceivePointsResponse retVal = base.Invoke<ReceivePointsRequest, ReceivePointsResponse>(info, request);
        return retVal;
    }
    
    public bool ReceivePoints(int[] xcoords, int[] ycoords, System.DateTime[] times)
    {
        ReceivePointsRequest request = new ReceivePointsRequest(xcoords, ycoords, times);
        ReceivePointsResponse response = this.ReceivePoints(request);
        return response.ReceivePointsResult;
    }
    
    private MessageForDesktopResponse MessageForDesktop(MessageForDesktopRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://www.japanese-coach.com/IKanjiService/MessageForDesktop";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://www.japanese-coach.com/IKanjiService/MessageForDesktopResponse";
        info.ResponseIsWrapped = true;
        MessageForDesktopResponse retVal = base.Invoke<MessageForDesktopRequest, MessageForDesktopResponse>(info, request);
        return retVal;
    }

    /// <summary>
    /// Messages for desktop.
    /// </summary>
    /// <param name="messages">The messages.</param>
    /// <returns></returns>
    public bool MessageForDesktop(int messages)
    {
        MessageForDesktopRequest request = new MessageForDesktopRequest(messages);
        MessageForDesktopResponse response = this.MessageForDesktop(request);
        return response.MessageForDesktopResult;
    }
    
    private MessageForInputAreaResponse MessageForInputArea(MessageForInputAreaRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://www.japanese-coach.com/IKanjiService/MessageForInputArea";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://www.japanese-coach.com/IKanjiService/MessageForInputAreaResponse";
        info.ResponseIsWrapped = true;
        MessageForInputAreaResponse retVal = base.Invoke<MessageForInputAreaRequest, MessageForInputAreaResponse>(info, request);
        return retVal;
    }
    
    public bool MessageForInputArea(int messages)
    {
        MessageForInputAreaRequest request = new MessageForInputAreaRequest(messages);
        MessageForInputAreaResponse response = this.MessageForInputArea(request);
        return response.MessageForInputAreaResult;
    }
    
    private GetNewMessagesForMobileResponse GetNewMessagesForMobile(GetNewMessagesForMobileRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://www.japanese-coach.com/IKanjiService/GetNewMessagesForMobile";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://www.japanese-coach.com/IKanjiService/GetNewMessagesForMobileResponse";
        info.ResponseIsWrapped = true;
        GetNewMessagesForMobileResponse retVal = base.Invoke<GetNewMessagesForMobileRequest, GetNewMessagesForMobileResponse>(info, request);
        return retVal;
    }
    
    public int GetNewMessagesForMobile()
    {
        GetNewMessagesForMobileRequest request = new GetNewMessagesForMobileRequest();
        GetNewMessagesForMobileResponse response = this.GetNewMessagesForMobile(request);
        return response.GetNewMessagesForMobileResult;
    }
    
    private GetNewMessagesForDesktopResponse GetNewMessagesForDesktop(GetNewMessagesForDesktopRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://www.japanese-coach.com/IKanjiService/GetNewMessagesForDesktop";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://www.japanese-coach.com/IKanjiService/GetNewMessagesForDesktopResponse";
        info.ResponseIsWrapped = true;
        GetNewMessagesForDesktopResponse retVal = base.Invoke<GetNewMessagesForDesktopRequest, GetNewMessagesForDesktopResponse>(info, request);
        return retVal;
    }
    
    public int GetNewMessagesForDesktop()
    {
        GetNewMessagesForDesktopRequest request = new GetNewMessagesForDesktopRequest();
        GetNewMessagesForDesktopResponse response = this.GetNewMessagesForDesktop(request);
        return response.GetNewMessagesForDesktopResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/ReceivePoints", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/ReceivePoints", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/MessageForDesktop", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/MessageForDesktop", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/MessageForInputArea", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/MessageForInputArea", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/GetNewMessagesForMobile", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/GetNewMessagesForMobile", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/GetNewMessagesForDesktop", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://www.japanese-coach.com/IKanjiService/GetNewMessagesForDesktop", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/ReceivePointsResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/ReceivePointsResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/MessageForDesktopResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/MessageForDesktopResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/MessageForInputAreaResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/MessageForInputAreaResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/GetNewMessagesForMobileResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/GetNewMessagesForMobileResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/GetNewMessagesForDesktopResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://www.japanese-coach.com/IKanjiService/GetNewMessagesForDesktopResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
