//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.japanese-coach.com", ConfigurationName="IKanjiService")]
public interface IKanjiService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.japanese-coach.com/IKanjiService/ReceivePoints", ReplyAction="http://www.japanese-coach.com/IKanjiService/ReceivePointsResponse")]
    bool ReceivePoints(int[] xcoords, int[] ycoords, System.DateTime[] times);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IKanjiServiceChannel : IKanjiService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class KanjiServiceClient : System.ServiceModel.ClientBase<IKanjiService>, IKanjiService
{
    
    public KanjiServiceClient()
    {
    }
    
    public KanjiServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public KanjiServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public KanjiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public KanjiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool ReceivePoints(int[] xcoords, int[] ycoords, System.DateTime[] times)
    {
        return base.Channel.ReceivePoints(xcoords, ycoords, times);
    }
}
