//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMessageReceiver
{
    
    int ReceiveMessage(int[] xcoords, int[] ycoords, System.DateTime[] times);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ReceiveMessage", Namespace="http://opennetcf.wcf.sample")]
public partial class ReceiveMessageRequest
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://opennetcf.wcf.sample", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
    public int[] xcoords;
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://opennetcf.wcf.sample", Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
    public int[] ycoords;
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://opennetcf.wcf.sample", Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
    public System.DateTime[] times;
    
    public ReceiveMessageRequest()
    {
    }
    
    public ReceiveMessageRequest(int[] xcoords, int[] ycoords, System.DateTime[] times)
    {
        this.xcoords = xcoords;
        this.ycoords = ycoords;
        this.times = times;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="ReceiveMessageResponse", Namespace="http://opennetcf.wcf.sample")]
public partial class ReceiveMessageResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://opennetcf.wcf.sample", Order=0)]
    public int ReceiveMessageResult;
    
    public ReceiveMessageResponse()
    {
    }
    
    public ReceiveMessageResponse(int ReceiveMessageResult)
    {
        this.ReceiveMessageResult = ReceiveMessageResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MessageReceiverClient : Microsoft.Tools.ServiceModel.CFClientBase<IMessageReceiver>, IMessageReceiver
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://localhost:8000/msgreceiver/MessageReceiver");
    
    public MessageReceiverClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public MessageReceiverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private ReceiveMessageResponse ReceiveMessage(ReceiveMessageRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://opennetcf.wcf.sample/IMessageReceiver/ReceiveMessage";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://opennetcf.wcf.sample/IMessageReceiver/ReceiveMessageResponse";
        info.ResponseIsWrapped = true;
        ReceiveMessageResponse retVal = base.Invoke<ReceiveMessageRequest, ReceiveMessageResponse>(info, request);
        return retVal;
    }
    
    public int ReceiveMessage(int[] xcoords, int[] ycoords, System.DateTime[] times)
    {
        ReceiveMessageRequest request = new ReceiveMessageRequest(xcoords, ycoords, times);
        ReceiveMessageResponse response = this.ReceiveMessage(request);
        return response.ReceiveMessageResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://opennetcf.wcf.sample/IMessageReceiver/ReceiveMessage", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://opennetcf.wcf.sample/IMessageReceiver/ReceiveMessage", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://opennetcf.wcf.sample/IMessageReceiver/ReceiveMessageResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://opennetcf.wcf.sample/IMessageReceiver/ReceiveMessageResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
